In [2]:
import torch

In [3]:
X =torch.tensor([[1.0,4.0,7.0], [2.0,3.0,6.0]])
X

tensor([[1., 4., 7.],
        [2., 3., 6.]])

In [4]:
X.shape

torch.Size([2, 3])

In [5]:
X.dtype

torch.float32

In [6]:
X[0,1]

tensor(4.)

In [7]:
X[:,1]

tensor([4., 3.])

In [8]:
10 * (X + 1.0)

tensor([[20., 50., 80.],
        [30., 40., 70.]])

In [9]:
X.exp()

tensor([[   2.7183,   54.5981, 1096.6332],
        [   7.3891,   20.0855,  403.4288]])

In [10]:
X.mean()

tensor(3.8333)

In [11]:
X.max(dim=0)

torch.return_types.max(
values=tensor([2., 4., 7.]),
indices=tensor([1, 0, 0]))

In [12]:
X @ X.T

tensor([[66., 56.],
        [56., 49.]])

In [14]:
import numpy as np
X.numpy()

array([[1., 4., 7.],
       [2., 3., 6.]], dtype=float32)

In [15]:
torch.tensor(np.array([[1.,4.,7.],[2.,3.,6.]]))

tensor([[1., 4., 7.],
        [2., 3., 6.]], dtype=torch.float64)

In [16]:
torch.FloatTensor(np.array([[1.,4.,7.],[2.,3.,6.]]))

tensor([[1., 4., 7.],
        [2., 3., 6.]])

In [18]:
X[:,1] = -99
X

tensor([[  1., -99.,   7.],
        [  2., -99.,   6.]])

In [19]:
X.relu_()
X

tensor([[1., 0., 7.],
        [2., 0., 6.]])

In [21]:
if torch.cuda.is_available():
    device = 'cuda'
elif torch.backends.mps.is_available():
    device = 'mps'
else:
    device = 'cpu'
device

'cpu'

In [22]:
import matplotlib.pyplot as plt

plt.rc('font', size=14)
plt.rc('axes', labelsize=14, titlesize=14)
plt.rc('legend', fontsize=14)
plt.rc('xtick', labelsize=10)
plt.rc('ytick', labelsize=10)

Matplotlib is building the font cache; this may take a moment.
